### ISSUE TITLE
Inconsistent colour for highlighting

### ISSUE THREAD

**Issue by tauraamui** [tauraamui/lilly#175]
![Screen recording 2024-07-19 10 12 52](https://github.com/user-attachments/assets/9ef9a16b-11b9-47c7-a620-7f9aa5a3b248)

For some reason each time Lilly starts the background/cell highlighting colour changes to a different shade when it should be consistently the same as what is set in the configuration.

At this time the cause is completely unknown and will require some investigation.

**Comment by wilsonk** [comment]
This doesn't happen for me on Arch linux when opening the same, or different files, from the command line twice (or more times), but it does happen if I use 'v' to highlight some lines and then escape out, but then use 'v' again to start highlighting again right away! 

It just seems to oscillate between two types of highlighting when I do this over and over. It doesn't change to 3 or more color schemes, just two. No idea what the problem is at this point.

**Comment by tauraamui** [comment]
Thank you sm for this additional information, I'll keep this in mind.

**Comment by tauraamui** [comment]
I've not seen this issue for a while now.
